export const enum WorkoutType {
  POWERLIFTING = 'POWERLIFTING',

  BODYBUILDING = 'BODYBUILDING',

  BODYBUILDING_CLASSIC = 'BODYBUILDING_CLASSIC',

  FITNESS = 'FITNESS',

  ENDURANCE = 'ENDURANCE',

  CARDIO = 'CARDIO',
}
