import 'package:adjust_specialist/model/body_composition.dart';
import 'package:adjust_specialist/model/client.dart';
import 'package:adjust_specialist/model/enum/activity_type.dart';
import 'package:adjust_specialist/model/enum/bmi_category.dart';
import 'package:adjust_specialist/model/enum/body_fat_category.dart';
import 'package:adjust_specialist/model/enum/body_frame_size.dart';
import 'package:adjust_specialist/model/enum/body_type.dart';
import 'package:adjust_specialist/model/enum/gender.dart';
import 'package:adjust_specialist/model/enum/goal.dart';
import 'package:adjust_specialist/model/enum/workout_location.dart';
import 'package:adjust_specialist/model/enum/workout_type.dart';

final BodyCompositionState bodyCompositionStateInit = BodyCompositionState(
    0,
    DateTime.now(),
    0,
    Gender.MALE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    BMICategory.EXTRAOBESE,
    0,
    0,
    0,
    BodyFatCategory.OBESE,
    0,
    0,
    BodyType.ENDOMORPH,
    0,
    BodyFrameSize.LARGE,
    0,
    WorkoutLocation.GYM,
    Goal.DECREASEWEIGHT,
    ActivityType.SEDENTARY,
    WorkoutType.FITNESS);

class BodyCompositionState extends BodyComposition {
  BodyCompositionState(
      int id,
      DateTime createdAt,
      int age,
      Gender gender,
      double height,
      double weight,
      double wrist,
      double waist,
      double hip,
      double abdomen,
      double neck,
      double waistHipRatio,
      double idealWeightMin,
      double idealWeightMax,
      double bestWeight,
      double bmi,
      BMICategory bmiCategory,
      double bmr,
      double lbm,
      double pbf,
      BodyFatCategory bodyFatCategory,
      double smm,
      double bodyTypeNumber,
      BodyType bodyType,
      double frameSize,
      BodyFrameSize bodyFrameSize,
      double visceralFatLevel,
      WorkoutLocation workoutLocation,
      Goal goal,
      ActivityType activityType,
      WorkoutType workoutType)
      : super(
            id,
            createdAt,
            age,
            gender,
            height,
            weight,
            wrist,
            waist,
            hip,
            abdomen,
            neck,
            waistHipRatio,
            idealWeightMin,
            idealWeightMax,
            bestWeight,
            bmi,
            bmiCategory,
            bmr,
            lbm,
            pbf,
            bodyFatCategory,
            smm,
            bodyTypeNumber,
            bodyType,
            frameSize,
            bodyFrameSize,
            visceralFatLevel,
            workoutLocation,
            goal,
            activityType,
            workoutType);
}
